/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_richardsonlainez;

import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author RALC
 */
public class Principa extends javax.swing.JFrame {
    
    /**
     * Creates new form Principa
     */
    public DefaultListModel modelo_lista_jugadores;
    public DefaultListModel modelo_lista_equipos;
    public int pos_seleccionado;
    public int pos_seleccionado_jugadores;
    public Principa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Crear_Equipos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombre_equipo = new javax.swing.JTextField();
        sp_copas_ganadas = new javax.swing.JSpinner();
        tf_estadio = new javax.swing.JTextField();
        jb_crear_equipo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_lista_equipos = new javax.swing.JList<>();
        sp_presupuesto = new javax.swing.JSpinner();
        JD_Crear_Jugadores = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_nombre_jugador = new javax.swing.JTextField();
        sp_habilidad = new javax.swing.JSpinner();
        sp_tecnica = new javax.swing.JSpinner();
        sp_precio_jugador = new javax.swing.JSpinner();
        cb_posiciones = new javax.swing.JComboBox<>();
        sp_resistencia_fisica = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_lista_jugadores = new javax.swing.JList<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        JD_Mostrar = new javax.swing.JDialog();
        jd_modificar_eliminar = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_equipos_modificar_eliminar = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_jugadores_modificar_eliminar = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jpop_equipos = new javax.swing.JPopupMenu();
        Modificar_equipo = new javax.swing.JMenuItem();
        Eliminar_equipo = new javax.swing.JMenuItem();
        jpop_jugadores = new javax.swing.JPopupMenu();
        Modificar_jugadores = new javax.swing.JMenuItem();
        Eliminar_jugadores = new javax.swing.JMenuItem();
        modificar_equipos = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tf_nombre_equipo_modificar = new javax.swing.JTextField();
        sp_copas_ganadas_modificar = new javax.swing.JSpinner();
        tf_estadio_modificar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sp_presupuesto_modificar = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JD_modificar_jugadores = new javax.swing.JDialog();
        sp_precio_jugador1 = new javax.swing.JSpinner();
        cb_posiciones1 = new javax.swing.JComboBox<>();
        tf_nombre_jugador1 = new javax.swing.JTextField();
        sp_resistencia_fisica1 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sp_habilidad1 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        sp_tecnica1 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        JD_comprar_Jugadores = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_equipos_comprar = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_jugadores_comprar = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Presupuesto");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Copas Ganadas");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Estadio");

        jb_crear_equipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_crear_equipo.setText("Crear Equipo");
        jb_crear_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crear_equipoActionPerformed(evt);
            }
        });

        jl_lista_equipos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_lista_equipos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        sp_presupuesto.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 10.0d));

        javax.swing.GroupLayout JD_Crear_EquiposLayout = new javax.swing.GroupLayout(JD_Crear_Equipos.getContentPane());
        JD_Crear_Equipos.getContentPane().setLayout(JD_Crear_EquiposLayout);
        JD_Crear_EquiposLayout.setHorizontalGroup(
            JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(tf_nombre_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(sp_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47)
                                .addComponent(sp_copas_ganadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(61, 61, 61)
                                .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jb_crear_equipo)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        JD_Crear_EquiposLayout.setVerticalGroup(
            JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Crear_EquiposLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sp_copas_ganadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_Crear_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jb_crear_equipo)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        JD_Crear_Jugadores.setBackground(new java.awt.Color(51, 0, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Precio");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Poscición");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Habilidad");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tecnica");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Resistencia Fisica");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Crear Jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sp_habilidad.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        sp_tecnica.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        sp_precio_jugador.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        cb_posiciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atacante", "Mediocampista", "Defensa", "Portero" }));

        sp_resistencia_fisica.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        jl_lista_jugadores.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_lista_jugadores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_Crear_JugadoresLayout = new javax.swing.GroupLayout(JD_Crear_Jugadores.getContentPane());
        JD_Crear_Jugadores.getContentPane().setLayout(JD_Crear_JugadoresLayout);
        JD_Crear_JugadoresLayout.setHorizontalGroup(
            JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Crear_JugadoresLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombre_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_posiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_resistencia_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_precio_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
            .addGroup(JD_Crear_JugadoresLayout.createSequentialGroup()
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_Crear_JugadoresLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jButton1))
                    .addGroup(JD_Crear_JugadoresLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        JD_Crear_JugadoresLayout.setVerticalGroup(
            JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Crear_JugadoresLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombre_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sp_precio_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_posiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(sp_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_Crear_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(sp_resistencia_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_MostrarLayout = new javax.swing.GroupLayout(JD_Mostrar.getContentPane());
        JD_Mostrar.getContentPane().setLayout(JD_MostrarLayout);
        JD_MostrarLayout.setHorizontalGroup(
            JD_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        JD_MostrarLayout.setVerticalGroup(
            JD_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jl_equipos_modificar_eliminar.setModel(new DefaultListModel()
        );
        jl_equipos_modificar_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_equipos_modificar_eliminarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_equipos_modificar_eliminar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jl_jugadores_modificar_eliminar.setModel(new DefaultListModel()
        );
        jl_jugadores_modificar_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadores_modificar_eliminarMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jl_jugadores_modificar_eliminar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Equipos");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Jugadores");

        javax.swing.GroupLayout jd_modificar_eliminarLayout = new javax.swing.GroupLayout(jd_modificar_eliminar.getContentPane());
        jd_modificar_eliminar.getContentPane().setLayout(jd_modificar_eliminarLayout);
        jd_modificar_eliminarLayout.setHorizontalGroup(
            jd_modificar_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                .addGroup(jd_modificar_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                        .addGroup(jd_modificar_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jLabel13))
                            .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_eliminarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        jd_modificar_eliminarLayout.setVerticalGroup(
            jd_modificar_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jd_modificar_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Modificar_equipo.setText("Modificar");
        Modificar_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_equipoActionPerformed(evt);
            }
        });
        jpop_equipos.add(Modificar_equipo);

        Eliminar_equipo.setText("Eliminar");
        Eliminar_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_equipoActionPerformed(evt);
            }
        });
        jpop_equipos.add(Eliminar_equipo);

        Modificar_jugadores.setText("Modificar");
        Modificar_jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_jugadoresActionPerformed(evt);
            }
        });
        jpop_jugadores.add(Modificar_jugadores);

        Eliminar_jugadores.setText("Eliminar");
        Eliminar_jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_jugadoresActionPerformed(evt);
            }
        });
        jpop_jugadores.add(Eliminar_jugadores);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Estadio");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Nombre");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Presupuesto");

        sp_presupuesto_modificar.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 10.0d));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Copas Ganadas");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificar_equiposLayout = new javax.swing.GroupLayout(modificar_equipos.getContentPane());
        modificar_equipos.getContentPane().setLayout(modificar_equiposLayout);
        modificar_equiposLayout.setHorizontalGroup(
            modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_equiposLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificar_equiposLayout.createSequentialGroup()
                        .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modificar_equiposLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(tf_nombre_equipo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modificar_equiposLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(sp_presupuesto_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(modificar_equiposLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(47, 47, 47)
                        .addComponent(sp_copas_ganadas_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificar_equiposLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(61, 61, 61)
                        .addComponent(tf_estadio_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificar_equiposLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton2)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        modificar_equiposLayout.setVerticalGroup(
            modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificar_equiposLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_nombre_equipo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sp_presupuesto_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sp_copas_ganadas_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificar_equiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tf_estadio_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton2)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        sp_precio_jugador1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        cb_posiciones1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atacante", "Mediocampista", "Defensa", "Portero" }));

        sp_resistencia_fisica1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Nombre");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Precio");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Poscición");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Habilidad");

        sp_habilidad1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Tecnica");

        sp_tecnica1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 10.0d));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Resistencia Fisica");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_modificar_jugadoresLayout = new javax.swing.GroupLayout(JD_modificar_jugadores.getContentPane());
        JD_modificar_jugadores.getContentPane().setLayout(JD_modificar_jugadoresLayout);
        JD_modificar_jugadoresLayout.setHorizontalGroup(
            JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_modificar_jugadoresLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombre_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_posiciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_resistencia_fisica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_precio_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(JD_modificar_jugadoresLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_modificar_jugadoresLayout.setVerticalGroup(
            JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_modificar_jugadoresLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(tf_nombre_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(sp_precio_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_posiciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(sp_habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(sp_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_modificar_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(sp_resistencia_fisica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Equipos");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Jugadores");

        jl_equipos_comprar.setModel(new DefaultListModel()
        );
        jl_equipos_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_equipos_comprarMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jl_equipos_comprar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jl_jugadores_comprar.setModel(new DefaultListModel()
        );
        jl_jugadores_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadores_comprarMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jl_jugadores_comprar);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_comprar_JugadoresLayout = new javax.swing.GroupLayout(JD_comprar_Jugadores.getContentPane());
        JD_comprar_Jugadores.getContentPane().setLayout(JD_comprar_JugadoresLayout);
        JD_comprar_JugadoresLayout.setHorizontalGroup(
            JD_comprar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_comprar_JugadoresLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(JD_comprar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(JD_comprar_JugadoresLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_comprar_JugadoresLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(JD_comprar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_comprar_JugadoresLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_comprar_JugadoresLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        JD_comprar_JugadoresLayout.setVerticalGroup(
            JD_comprar_JugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_comprar_JugadoresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg5_richardsonlainez/Champions-League-Final.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenu3.setText("Crear");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Equipos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Jugadores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenu4.setText("Modificar/Eliminar");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Equipos/Jugadores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu1.add(jMenu4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Compar/Trasferencia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // PARA A LA LISTA
        DefaultListModel modelo= (DefaultListModel) jl_lista_jugadores.getModel();
        modelo.addElement(new Jugadores(tf_nombre_jugador.getText(), (double)sp_precio_jugador.getValue(),
                cb_posiciones.getSelectedItem().toString(), false, (double)sp_habilidad.getValue(), (double)sp_tecnica.getValue(), 
                (double)sp_resistencia_fisica.getValue()));
        jl_lista_jugadores.setModel(modelo);
        this.modelo_lista_jugadores = modelo;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JD_Crear_Jugadores.setVisible(true);
        this.JD_Crear_Jugadores.setModal(true);
        JD_Crear_Jugadores.pack();
        JD_Crear_Jugadores.setLocationRelativeTo(jPanel1);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jb_crear_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crear_equipoActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_lista_equipos.getModel();
        modelo.addElement(new Equipos(tf_nombre_equipo.getText(), (double)sp_presupuesto.getValue(), 
                (int)sp_copas_ganadas.getValue(), tf_estadio.getText()));
        jl_lista_equipos.setModel(modelo);
        this.modelo_lista_equipos = modelo;
    }//GEN-LAST:event_jb_crear_equipoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JD_Crear_Equipos.setVisible(true);
        this.JD_Crear_Equipos.setModal(true);
        JD_Crear_Equipos.pack();
        JD_Crear_Equipos.setLocationRelativeTo(jPanel1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jd_modificar_eliminar.setVisible(true);
        this.jd_modificar_eliminar.setModal(true);
        jd_modificar_eliminar.pack();
        jd_modificar_eliminar.setLocationRelativeTo(jPanel1);
        jl_equipos_modificar_eliminar.setModel(modelo_lista_equipos);
        jl_jugadores_modificar_eliminar.setModel(modelo_lista_jugadores);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jl_equipos_modificar_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_equipos_modificar_eliminarMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown()){
            pos_seleccionado = jl_equipos_modificar_eliminar.getSelectedIndex();
            jpop_equipos.show(evt.getComponent(), 
                        evt.getX(), evt.getY()); 
        }///AQUI NOS QUEDAMOS
        
    }//GEN-LAST:event_jl_equipos_modificar_eliminarMouseClicked

    private void Modificar_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_equipoActionPerformed
        // TODO add your handling code here:JD_Crear_Equipos.setVisible(true);
        this.modificar_equipos.setModal(true);
        modificar_equipos.pack();
        modificar_equipos.setLocationRelativeTo(this.jd_modificar_eliminar);
        modificar_equipos.setVisible(true);
    }//GEN-LAST:event_Modificar_equipoActionPerformed

    private void Eliminar_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_equipoActionPerformed
        // TODO add your handling code here:
        modelo_lista_equipos.remove(pos_seleccionado);
        
    }//GEN-LAST:event_Eliminar_equipoActionPerformed

    private void Eliminar_jugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_jugadoresActionPerformed
        // TODO add your handling code here:
        modelo_lista_jugadores.remove(pos_seleccionado_jugadores);
    }//GEN-LAST:event_Eliminar_jugadoresActionPerformed

    private void jl_jugadores_modificar_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadores_modificar_eliminarMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown()){
            pos_seleccionado = jl_jugadores_modificar_eliminar.getSelectedIndex();
            jpop_jugadores.show(evt.getComponent(), 
                        evt.getX(), evt.getY()); 
        }///AQUI NOS QUEDAMOS
    }//GEN-LAST:event_jl_jugadores_modificar_eliminarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Equipos q = new Equipos(tf_nombre_equipo_modificar.getText(), (double) sp_presupuesto_modificar.getValue(), 
                (int)sp_copas_ganadas_modificar.getValue(), tf_estadio_modificar.getText());
        modelo_lista_equipos.remove(pos_seleccionado);
        modelo_lista_equipos.addElement(q);
        modificar_equipos.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Jugadores j = new Jugadores(tf_nombre_jugador1.getText(), (double)sp_precio_jugador1.getValue(),
                cb_posiciones1.getSelectedItem().toString(), false, (double)sp_habilidad1.getValue(), (double)sp_tecnica1.getValue(), 
                (double)sp_resistencia_fisica1.getValue());
        modelo_lista_jugadores.remove(pos_seleccionado_jugadores);
        modelo_lista_jugadores.addElement(j);
        JD_modificar_jugadores.dispose();
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Modificar_jugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_jugadoresActionPerformed
        // TODO add your handling code here:
         this.JD_modificar_jugadores.setModal(true);
        JD_modificar_jugadores.pack();
        JD_modificar_jugadores.setLocationRelativeTo(this.jd_modificar_eliminar);
        JD_modificar_jugadores.setVisible(true);
        
    }//GEN-LAST:event_Modificar_jugadoresActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        this.JD_comprar_Jugadores.setModal(true);
        JD_comprar_Jugadores.pack();
        JD_comprar_Jugadores.setLocationRelativeTo(this);
        JD_comprar_Jugadores.setVisible(true);
        jl_equipos_comprar.setModel(modelo_lista_equipos);
        jl_jugadores_comprar.setModel(modelo_lista_jugadores);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jl_equipos_comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_equipos_comprarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_equipos_comprarMouseClicked

    private void jl_jugadores_comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadores_comprarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_jugadores_comprarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar_equipo;
    private javax.swing.JMenuItem Eliminar_jugadores;
    private javax.swing.JDialog JD_Crear_Equipos;
    private javax.swing.JDialog JD_Crear_Jugadores;
    private javax.swing.JDialog JD_Mostrar;
    private javax.swing.JDialog JD_comprar_Jugadores;
    private javax.swing.JDialog JD_modificar_jugadores;
    private javax.swing.JMenuItem Modificar_equipo;
    private javax.swing.JMenuItem Modificar_jugadores;
    private javax.swing.JComboBox<String> cb_posiciones;
    private javax.swing.JComboBox<String> cb_posiciones1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_crear_equipo;
    private javax.swing.JDialog jd_modificar_eliminar;
    private javax.swing.JList<String> jl_equipos_comprar;
    private javax.swing.JList<String> jl_equipos_modificar_eliminar;
    private javax.swing.JList<String> jl_jugadores_comprar;
    private javax.swing.JList<String> jl_jugadores_modificar_eliminar;
    private javax.swing.JList<String> jl_lista_equipos;
    private javax.swing.JList<String> jl_lista_jugadores;
    private javax.swing.JPopupMenu jpop_equipos;
    private javax.swing.JPopupMenu jpop_jugadores;
    private javax.swing.JDialog modificar_equipos;
    private javax.swing.JSpinner sp_copas_ganadas;
    private javax.swing.JSpinner sp_copas_ganadas_modificar;
    private javax.swing.JSpinner sp_habilidad;
    private javax.swing.JSpinner sp_habilidad1;
    private javax.swing.JSpinner sp_precio_jugador;
    private javax.swing.JSpinner sp_precio_jugador1;
    private javax.swing.JSpinner sp_presupuesto;
    private javax.swing.JSpinner sp_presupuesto_modificar;
    private javax.swing.JSpinner sp_resistencia_fisica;
    private javax.swing.JSpinner sp_resistencia_fisica1;
    private javax.swing.JSpinner sp_tecnica;
    private javax.swing.JSpinner sp_tecnica1;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_estadio_modificar;
    private javax.swing.JTextField tf_nombre_equipo;
    private javax.swing.JTextField tf_nombre_equipo_modificar;
    private javax.swing.JTextField tf_nombre_jugador;
    private javax.swing.JTextField tf_nombre_jugador1;
    // End of variables declaration//GEN-END:variables
}
